sudo: required
services:
  - docker
  
before_install:
  - docker build -t lwlmm/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lwlmm/multi-docker-test npm run test

after_success:
  - docker build -t lwlmm/multi-client ./client
  - docker build -t lwlmm/multi-nginx ./nginx
  - docker build -t lwlmm/multi-server ./server
  - docker build -t lwlmm/multi-worker ./worker

# log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to DockerHub
  - docker push lwlmm/multi-client
  - docker push lwlmm/multi-nginx
  - docker push lwlmm/multi-server
  - docker push lwlmm/multi-worker